### PR TITLE
Add dynamic vagrant hosts file

### PR DESCRIPTION
**Pull request by MathiasStadler**
Hallo Bert,
BTW your project is a great idea.
I add the possibility to used custom vagrant-hosts files, so i must not clone that project and delete the .git directory. I can hold the structure of the project.

I'm add the sample script custom-vagrant-host.yaml and add a description in the README.md  file.

I fix same github markdown issue follow these rules https://github.com/DavidAnson/markdownlint/blob/v0.6.4/doc/Rules.md 

Mathias

### CODE REVIEW

**Comment by reavon** [comment]
@MathiasStadler Where @bertvv has `$ git`, he is correct. Most unix users understand that `$` is a non-privliged user whereas `# git` would indicate a privileged user such as `root` in this instance.

It's a nuance and shouldn't really matter. Just an FYI.

**Comment by bertvv** [comment]
Thanks, I like this PR! However, you forgot to add your name to the contributors... :-) If you do, I'll do the merge.

I always use `$` or `#` as prompt just like @reavon mentions, but I don't really have an Opinion about this, so your proposed change is fine by me.

Thank you very much for your contribution!

**Comment by garfieldcoked** [comment]
@bertvv Just found your blog post which led me here. I must say fantastic work, thank you. I currently have a lot of vagrant files that I was using environment variables to select the correct one when I did vagrant up. 

This also means I have a lot of different environments I am creating and this PR was the first thing that came to mind so thank you @MathiasStadler.

**Comment by bertvv** [comment]
Hey @MathiasStadler, sorry it took so long to merge your PR! Thank you @garfieldcoked for the comment, that reminded me...

**Pull request merged**
